name: yeaseul_t_infinity_assignment
description: A T_Infinity_Assignment

publish_to: 'none'
# pub.dev에 배포하고 싶으면 해당 줄 삭제하면 된다.

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
#외부 패키지 의존성
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  timezone: ^0.9.2
  intl: ^0.18.1

dev_dependencies:
# 개발할 때만 필요한 의존성
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
#flutter의 material design을 사용한다.